### ISSUE TITLE
Compiler error when running dynamic router server-side

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro-incubator#16]
```
Caused by: java.lang.IllegalStateException: var: #'fulcro.incubator.dynamic-routing/current-route-class is not public
```
I'm guessing it's because `defrouter` is a macro spitting out this line https://github.com/fulcrologic/fulcro-incubator/blob/develop/src/main/fulcro/incubator/dynamic_routing.cljc#L466

So this private function gets called in userland.

**Comment by awkay** [comment]
Fixed a permission fix in 0.0.26.
