### ISSUE TITLE
(Dynamic Routing) Console warnings about router state machines not being in fulcro state

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro-incubator#26]
```
Attempt to get an ASM path [:fulcro.incubator.ui-state-machines/local-storage :path-segment] for a state machine that is not in Fulcro state. ASM ID:  :RootRouter

Attempt to get an ASM path [:fulcro.incubator.ui-state-machines/local-storage :pending-path-segment] for a state machine that is not in Fulcro state. ASM ID:  :RootRouter
```

**Comment by awkay** [comment]
Does this seem to affect functionality?

**Comment by levitanong** [comment]
I think because of this, `defrouter`'s render body is rendered useless, because all the value in its prop are nil.

**Comment by awkay** [comment]
Are you remembering to call `change-route` on mount?  I cannot fix this if I don't understand what is happening.  The first call to `change-route` is what starts the state machine for the routing system.

**Comment by levitanong** [comment]
I have not forgotten to call change-route on mount. Problem exists despite that call. :(

**Comment by awkay** [comment]
see the pr I sent
