### ISSUE TITLE
As of 0.0.23, pessimistic mutations don't properly merge-join responses with nested queries

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro-incubator#29]
Minimal repro to follow

**Comment by levitanong** [comment]
Minimal repro: https://github.com/levitanong/repro-incubator-29

1. `shadow-cljs compile app`
2. visit localhost:8000
3. Note error message about assoc.

`0.0.22` is the last working version of incubator
`0.0.23` is when it starts breaking (still broken at 0.0.30)

**Comment by awkay** [comment]
@wilkerlucio 0.0.23 was the change to added the pessimistic mutation key.  It is causing some kind of problem in fulcro-proper against the mark missing operation (it is a mutation query with [*] as the query), so perhaps mark-missing doesn't like that.  I'll check further, but if this rings any bells let me know.

**Comment by awkay** [comment]
@levitanong @wilkerlucio I think I found the issue. Release 0.0.31-SNAPSHOT to clojars.

Wilker, the mutation response was already normalized into the mutation response swap, so a simple get-in to pull it and then use it against `merge-component!` sent a non-normalized data tree to that function, resulting in badness.

Pls take a look at the PR and see if the fix looks right to you, and possibly test it against existing code.

**Comment by awkay** [comment]
Fixed in 0.0.31
