### ISSUE TITLE
defsc-route-target does not work without :query

### ISSUE THREAD

**Issue by MrEbbinghaus** [fulcrologic/fulcro-incubator#31]
I get `Uncaught #error {:message "Invalid join, {:fulcro.incubator.dynamic-routing/current-route nil}, :data {:type :error/invalid-join}}`,
if I have a `defsc-route-target` without a query (not only, when I am routing to the target).

I have to write `:query []` for my route-target to work.

**Comment by awkay** [comment]
Not a bug.  Routes and route targets have to be stateful  components with queries (and probably idents).  Dynamic routing uses query traversal to work.
