### ISSUE TITLE
(state machines) Warn on remote mutation against unmounted component

### ISSUE THREAD

**Issue by levitanong** [fulcrologic/fulcro-incubator#35]
In the state machine docs, actor must be a mounted component or else remote mutations are aborted. It would be a big usability boost if some warning was raised about a remote mutation executed against an unmounted component.

https://github.com/fulcrologic/fulcro-incubator/blob/develop/state-machine-docs.adoc#mutations-and-state-machines

**Comment by awkay** [comment]
I think it already has one: https://github.com/fulcrologic/fulcro-incubator/blob/develop/src/main/fulcro/incubator/ui_state_machines.cljc#L540

If you're seeing a case where that's not true, be interested in a repro.

**Comment by levitanong** [comment]
I think this is happening to me when there's a route change in parallel with this, such that when remote mutation is triggered, the actor is still mounted, but is dismounted sometime after the check happens.

**Comment by awkay** [comment]
I made some changes to this in F3 that might fix this.  I could be influenced to back-port that kind of fix, but I'm not terribly motivated to do so at the moment.  You could look at diffs between this version and the f3 source, try applying changes and see if it helps.

**Comment by levitanong** [comment]
IMHO not worth back-porting if it's already fixed in f3, especially since I can just work around this problem by using a persistent top level component as an actor.
